#!/bin/sh
#
# Create symlinks for all the dotfiles

LINK='ln -sf'
DOTFILES_ROOT=$(pwd)

set -e

# bash
$LINK $DOTFILES_ROOT/bash/.??* $HOME/

# zsh
$LINK $DOTFILES_ROOT/zsh/.??* $HOME/

# sublime text
$LINK $DOTFILES_ROOT/sublime/User $HOME/.config/sublime-text-3/Packages/

# nano
$LINK $DOTFILES_ROOT/.nanorc $HOME/

# vi
$LINK $DOTFILES_ROOT/.vimrc $HOME/

# git
$LINK $DOTFILES_ROOT/.gitconfig $HOME/

# aliases
$LINK $DOTFILES_ROOT/.aliases $HOME/
